### PR TITLE
Signin/signout

### PR DESCRIPTION
**Pull request by lectrician1**
Basic login/logout site security. you need to create a new account on the supabase dashboard in the auth section and login with that.

The logout button needs to be like refactored in the sidebar file? Not mandatory for merging but can do it if you want.

When logging out the login page doesn't rerender correctly. I don't know if the session management in `root.tsx` is the best to manage this.

### CODE REVIEW

**Comment by EthanDawes** [comment]
I see you've added spaces around curly braces. Did you do this or did it happen automatically? Is this something that we should make consistent project-wide? I personally think it looks fine w/o a space, but I don't care too much if we're going to pick.

**Comment by EthanDawes** [comment]
I noticed it put the credentials in the url a few times which isn't great but wasn't able to reproduce, so look out for that and let me know if it happens

**Comment by EthanDawes** [comment]
It's not great that it flashes the signin screen even if the user is already authenticated, but that seems to be an effect of server side rendering (server won't be signed into any accounts).

Idk how, but it seems like switching session signal to a resource fixed the rendering bug when signing out, can confirm?

**Review by EthanDawes — APPROVED** [review]

**Comment by lectrician1** [comment]
> I see you've added spaces around curly braces. Did you do this or did it happen automatically? Is this something that we should make consistent project-wide? I personally think it looks fine w/o a space, but I don't care too much if we're going to pick.

That's what the VSCode auto-formatter does for typescript files when I press ctrl-shift-f. I know you use webstorm so it might do something different? if so maybe need a linter?

**Comment by lectrician1** [comment]
> I noticed it put the credentials in the url a few times which isn't great but wasn't able to reproduce, so look out for that and let me know if it happens

didn't check this but will test a few more times before merging

**Comment by lectrician1** [comment]
> It's not great that it flashes the signin screen even if the user is already authenticated, but that seems to be an effect of server side rendering (server won't be signed into any accounts).
> 
> Idk how, but it seems like switching session signal to a resource fixed the rendering bug when signing out, can confirm?

Yeah Idk how to exactly check if the session is valid every time. Maybe always render session-protected pages on client using onMount? I needed to research more how other sites do this but was lazy and just made this first implementation.

**Comment by EthanDawes** [comment]
> Yeah Idk how to exactly check if the session is valid every time. Maybe always render session-protected pages on client using onMount? I needed to research more how other sites do this but was lazy and just made this first implementation.

Well, the session is checked every time because the check is in `root.tsx`, which renders for every route. The issue I was mentioning was more of a visual one. I can think of two solutions. 1: on the server side, read the Authentication cookies and forward them to supabase or 2: disable SSR globally. Since SEO isn't a concern, I've gone ahead and implemented 2. With this, we may need to add more `<suspence>` boundries to make the app feel more responsive.

**Comment by lectrician1** [comment]
Disabling SSR sounds good. Thanks for fixing the sidebar code.

**Pull request merged**
